name: Build release files

on:
  push:
    branches: [master, develop]
    tags: ['v*']
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14 # M1
            package: darwin-universal
            extension: app
            source: out/make/zip/darwin/universal/Handbook*.zip
            target: out/make/Handbook-v{version}-darwin-arm64.zip
          - os: macos-13
            package: darwin-x64
            extension: app
            source: out/make/zip/darwin/x64/Handbook*.zip
            target: out/make/Handbook-v{version}-darwin-x64.zip
          - os: ubuntu-22.04
            package: linux-x64
            extension: deb
            source: out/make/deb/x64/handbook*.deb
            target: out/make/Handbook-v{version}-x64-Setup.deb
          - os: ubuntu-22.04
            package: linux-x64
            extension: rpm
            source: out/make/rpm/x64/Handbook*.rpm
            target: out/make/Handbook-v{version}-x64-Setup.rpm
          - os: windows-2022
            package: win32-x64
            extension: exe
            source: out/make/squirrel.windows/x64/Handbook*.exe
            target: out/make/Handbook-v{version}-x64-Setup.exe

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Extract Version from Tag
      id: extract_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-debug"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Update package.json with Version
      run: |
        node -e "let pkg=require('./package.json'); pkg.version='${{ env.VERSION }}'; require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));"
    
    # - name: Pre-make
    #   if: ${{ matrix.preMake }}
    #   run: ${{ matrix.preMake }}

    - name: Package ${{ matrix.package }}
      run: npm run package:${{ matrix.package }}

    - name: Make ${{ matrix.package }}
      run: npm run make:${{ matrix.package }}-${{ matrix.extension }} -- --skip-package

    - name: Rename Binaries
      run: |
        version=${{ env.VERSION }}
        target=${{ matrix.target }}
        target=${target/\{version\}/$version}
        mv ${{ matrix.source }} $target
        echo "RENAMED_TARGET=$target" >> $GITHUB_ENV
      shell: bash

    - name: Upload files to a GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.RENAMED_TARGET }}
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-nightly') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}