name: Build version

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14 #M1
            make: darwin-universal
            source: out/make/zip/darwin/universal/handbook*.zip
            target: out/make/handbook-darwin-universal.zip
          - os: macos-14 #M1
            make: darwin-arm64
            source: out/make/zip/darwin/arm64/handbook*.zip
            target: out/make/handbook-darwin-arm64.zip
          - os: macos-13
            make: darwin-x64
            source: out/make/zip/darwin/x64/handbook*.zip
            target: out/make/handbook-darwin-x64.zip
          - os: ubuntu-22.04
            make: linux-x64-deb
            source: out/make/deb/x64/handbook*.deb
            target: out/make/handbook-x64.deb
          - os: ubuntu-22.04
            make: linux-x64-rpm
            source: out/make/rpm/x64/handbook*.rpm
            target: out/make/handbook-x64.rpm
          - os: windows-2022
            make: win32-x64
            source: out/make/squirrel.windows/x64/handbook*.exe
            target: out/make/handbook-x64.exe

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Make ${{ matrix.make }}
      run: npm run make:${{ matrix.make }}

    - name: Rename Binaries
      run: mv ${{ matrix.source }} ${{ matrix.target }}

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.7.0
      with:
        file: ${{ matrix.target }}
        overwrite: true