name: Test build steps

on:
  push:
    branches: [ 'develop' ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14 # M1
            package: darwin-universal
            extension: app
            source: out/make/zip/darwin/universal/handbook*.zip
            target: out/make/handbook-darwin-arm64.zip
          - os: macos-13
            package: darwin-x64
            extension: app
            source: out/make/zip/darwin/x64/handbook*.zip
            target: out/make/handbook-darwin-x64.zip
          - os: ubuntu-22.04
            package: linux-x64
            extension: deb
            source: out/make/deb/x64/handbook*.deb
            target: out/make/handbook-x64.deb
          - os: ubuntu-22.04
            package: linux-x64
            extension: rpm
            source: out/make/rpm/x64/handbook*.rpm
            target: out/make/handbook-x64.rpm
          - os: windows-2022
            package: win32-x64
            extension: exe
            source: out/make/squirrel.windows/x64/handbook*.exe
            target: out/make/handbook-x64.exe

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Package ${{ matrix.package }}
      run: npm run package:${{ matrix.package }}

    # - name: Pre-make
    #   if: ${{ matrix.preMake }}
    #   run: ${{ matrix.preMake }}

    - name: Make ${{ matrix.package }}
      run: npm run make:${{ matrix.package }}-${{ matrix.extension }} -- --skip-package

    - name: Rename Binaries
      run: mv ${{ matrix.source }} ${{ matrix.target }}